version: "3"
volumes:
  mongodb_data:
    driver: local

services:
  app:
    container_name: leri_explore_backend_development
    build: .
    restart: always
    command: bash -c "node setup.js && node entry.js"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - postgres
    env_file:
        - docker.development.env

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    volumes:
      - ./data/postgres:/data/db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_DEFAULT_DB_ADMIN_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DEFAULT_DB_ADMIN_PASSWORD}
    #   - MONGO_INITDB_DATABASE=admin
