version: "2"
services:
  app:
    container_name: leri-explore-backend-dev
    image: deakinlaunchpad/leri-explore-backend-dev
    restart: always
    environment:
      - DB_USERNAME=leri_explore_admin
      - DB_PASSWORD=password
      - DB_DATABASE=leri_explore_dev
      - DB_HOST=postgres_leri_dev
    command: bash -c "node server.js"
    ports:
      - "8000:8000"
    links:
      - postgres_leri_dev
  postgres_leri_dev:
    container_name: postgres_leri_dev
    image: postgres:11
    environment:
      - POSTGRES_USER=leri_explore_admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leri_explore_dev
    volumes:
      - ./data:/data/leri-explore-backend-dev/db
    ports:
      - "54320:5432"
