version: "2"
services:
  app:
    container_name: leri_explore_backend_development
    build: .
    restart: always
    command: bash -c "node setup.js && node entry.js"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - mongo
      - postgres
    env_file:
      - docker.development.env

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    volumes:
      - ./data/postgres:/data/db
    # ports:
    #   - "5432:5432"
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}

  mongo:
    container_name: mongo
    image: mongo
    # restart: always
    volumes:
      - ./data/mongo:/data/db
    # ports:
    #   - "27018:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_DEFAULT_DB_ADMIN_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DEFAULT_DB_ADMIN_PASSWORD}
    #   - MONGO_INITDB_DATABASE=admin
